### ISSUE TITLE
Error after yarn build

### ISSUE THREAD

**Issue by danilsitnikov783** [ReactJSResources/react-webpack-babel#295]
Hi! Figured out with another problem. After build I open index.html. Looks fine and haven't any errors. But when I trid to switch route 'help' I see error in console:

`Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'file:///D:/help' cannot be created in a document with origin 'null' and URL 'file:///D:/frl/public/index.html'.
    at file:///D:/frl/public/bundle.js:22:50605`

What this? How I can fix this issue?

**Comment by pgerochi** [comment]
hey @danilsitnikov783 i'm not getting this issue but what browser are you using? I tried replicating this through firefox/chrome and it works fine for me. (using mac)

**Comment by danilsitnikov783** [comment]
@pgerochi Chrome, win 10. I modified configs for me. Maybe error in this. 

[webpack.config](https://pastebin.com/MWMMTFVw)
[webpack.production](https://pastebin.com/ZfJFtnhX)

**Comment by pgerochi** [comment]
@danilsitnikov783 when you open index.html in the build folder (public) are you running it on a server? If not, that may be your problem.

**Comment by alicoding** [comment]
URL 'file:///D:/help' so similar problem to the other one :) you need webserver to be able to run the application

**Comment by danilsitnikov783** [comment]
@alicoding which the server?) I need to setup .htaccess for looking index.html? And user for this some MAMP or XAMPP?

**Comment by danilsitnikov783** [comment]
@pgerochi No. I just opening index.html

**Comment by alicoding** [comment]
@danilsitnikov783 if you have python installed on your machine then run the following command inside `public` directory 

```
python -m SimpleHTTPServer 8000
```

then go to `localhost:8000` to see the content.

**Comment by alicoding** [comment]
I'm closing this issue since we have documented way to run the project
