### ISSUE TITLE
when type "npm start"  the server does not start

### ISSUE THREAD

**Issue by star-ter-js** [ReactJSResources/react-webpack-babel#298]
$ npm start

> react-webpack-babel@0.0.4 start C:\Users\p.bavaro\node-app\react-webpack-babel
> webpack-dev-server --progress --profile --colors

 10% building modules 1/1 modules 0 active                                                                                                                                          Project is running at http://127.0.0.1:8888/
webpack output is served from /
Content not from webpack is served from ./public
404s will fallback to /index.html     4440ms building modules                                                                                                                       2ms sealing
0ms optimizing
0ms basic module optimization
1ms module optimization
0ms advanced module optimization
0ms basic chunk optimization
0ms chunk optimization
1ms advanced chunk optimization
0ms module and chunk tree optimization
0ms chunk modules optimization
0ms advanced chunk modules optimization
2ms module reviving
2ms module order optimization
3ms module id optimization
0ms chunk reviving
0ms chunk order optimization
2ms chunk id optimization
8ms hashing
0ms module assets processing
390ms chunk assets processing
1ms additional chunk assets processing
0ms additional asset processing
0ms chunk asset optimization
37ms asset optimization
Hash: 3bbdee34693de1695896
Version: webpack 3.8.1
Time: 4870ms
 2 assets
[./node_modules/loglevel/lib/loglevel.js] ./node_modules/loglevel/lib/loglevel.j                                                                                                    s 7.86 kB {0} [built]
       [] -> factory:128ms building:1680ms = 1808ms
[./node_modules/react-hot-loader/patch.js] ./node_modules/react-hot-loader/patch                                                                                                    .js 40 bytes {0} [built]
       [] -> factory:58ms building:42ms = 100ms
[./node_modules/react/index.js] ./node_modules/react/index.js 190 bytes {0} [bui                                                                                                    lt]
       [] -> factory:546ms building:47ms dependencies:1ms = 594ms
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client                                                                                                    /socket.js 1.05 kB {0} [built]
       [] -> factory:37ms building:26ms = 63ms
   [0] multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-s                                                                                                    erver react-hot-loader/patch ./src/index.jsx 64 bytes {0} [built]
        factory:0ms building:2ms = 2ms
[./node_modules/strip-ansi/index.js] ./node_modules/strip-ansi/index.js 161 byte                                                                                                    s {0} [built]
       [] -> factory:126ms building:1001ms = 1127ms
[./node_modules/url/url.js] ./node_modules/url/url.js 23.3 kB {0} [built]
       [] -> factory:49ms building:65ms = 114ms
[./node_modules/webpack-dev-server/client/index.js?http://127.0.0.1:8888] (webpa                                                                                                    ck)-dev-server/client?http://127.0.0.1:8888 7.95 kB {0} [built]
       [] -> factory:53ms building:30ms dependencies:65ms = 148ms
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/clien                                                                                                    t/overlay.js 3.73 kB {0} [built]
       [] -> factory:37ms building:24ms = 61ms
[./node_modules/webpack/hot ^\.\/log$] (webpack)/hot nonrecursive ^\.\/log$ 170                                                                                                     bytes {0} [built]
       [] -> factory:36ms building:13ms dependencies:0ms = 49ms
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.56 kB {                                                                                                    0} [built]
       [] -> factory:58ms building:37ms = 95ms
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {0} [b                                                                                                    uilt]
       [] -> factory:33ms building:19ms = 52ms
[./src/app.jsx] ./src/app.jsx 1.15 kB {0} [built]
       [] -> factory:480ms building:63ms dependencies:470ms = 1013ms
[./src/index.jsx] ./src/index.jsx 952 bytes {0} [built]
       [] -> factory:214ms building:1673ms = 1887ms
[./src/routes.jsx] ./src/routes.jsx 1.15 kB {0} [built]
       [] -> factory:431ms building:93ms dependencies:22ms = 546ms
    + 264 hidden modules

ERROR in ./node_modules/css-loader?importLoaders=1!./node_modules/sass-loader/li                                                                                                    b/loader.js!./styles/index.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\p.bavaro\node-app\react-webpack-babel\node_m                                                                                                    odules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Users\p.bavaro\node-app\react-webpack-babel\node_modules\l                                                                                                    oader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\p.bavaro\node-app\react-webpack-babel\no                                                                                                    de_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\p.bavaro\node-app\react-webpack-babel\no                                                                                                    de_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\p.bavaro\node-app\react-webpack-babel\node_modules\loader-runner                                                                                                    \lib\LoaderRunner.js:173:18
 @ ./styles/index.scss 4:14-133 18:2-22:4 19:20-139
 @ ./src/routes.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-serve                                                                                                    r react-hot-loader/patch ./src/index.jsx
Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/template.html] ./nod                                                                                                    e_modules/html-webpack-plugin/lib/loader.js!./src/template.html 659 bytes {0} [b                                                                                                    uilt]
            factory:108ms building:34ms = 142ms
    [./node_modules/lodash/lodash.js] ./node_modules/lodash/lodash.js 540 kB {0}                                                                                                     [built]
           [] -> factory:72ms building:1000ms = 1072ms
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 488 b                                                                                                    ytes {0} [built]
           [] -> factory:689ms building:103ms = 792ms
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 495 b                                                                                                    ytes {0} [built]
           [] -> factory:689ms building:105ms = 794ms

**Comment by alicoding** [comment]
Could you show snippet of your code where you include that `sass`?

ERROR in ./node_modules/css-loader?importLoaders=1!./node_modules/sass-loader/li b/loader.js!./styles/index.scss

**Comment by alicoding** [comment]
@star-ter-js let me know if you still need help with this :)
