### ISSUE TITLE
.babelrc module-resolver breaks redux import

### ISSUE THREAD

**Issue by kidroca** [ReactJSResources/react-webpack-babel#299]
For some reason the current `.babelrc` config and specifically the `module-resolver` plugin prevents webpack to resolve `redux` exports correctly 

For this file:

```javascript
import { combineReducers } from 'redux';
import app from './app.reducer';
import temp from './temp.reducer';

const combinedReducers = combineReducers({
  app,
  temp
});

export default combinedReducers;
```

We've got an error like this during app initialization:
> Uncaught TypeError: (0 , _.combineReducers) is not a function

Removing the `module-resolver` plugin from the config and the import is resolved correctly then the app loads

Sample repository where I have recreated the issue https://github.com/kidroca/react-webpack-babel-issue-sample.

The change that I made to resolve my issue: https://github.com/kidroca/react-webpack-babel-issue-sample/commit/84fe3342ab3e0ceafa976ca9c56a166664ad53f9 this is available in the `temp-fix` branch

My OS is Windows 10 if that's have anything to do with this 

---

Another way to fix the issue without removing this plugin is to import from redux like this:
```
import { combineReducers } from 'redux/dist/redux';
```

This worked 
That's how I found out there is a problem with the module resolution

**Comment by alicoding** [comment]
Is this only a problem with Redux? 

@pgerochi did you encounter similar issue when you setup your project with redux here?

**Comment by kidroca** [comment]
redux was one of the first libraries that I added and the only one that had this issue then I removed the `module-resolver` from config

Maybe it has something to do with the package.json of the redux lib

**Comment by alicoding** [comment]
So, I don't know if this is an issue with Windows 10 with `module-resolver` specifically, but I just installed `redux` and was able to `import` this `combineReducers` function and logged it no problem... I'm trying to google around to see if this is a known issue in `module-resolver` itself or something, but to I'm wondering if you are able to use `webpack` alias as a workaround for now?

**Comment by alicoding** [comment]
@kidroca any update on your side? Is this still an issue for you? Should I close or find out the issue still?

**Comment by kidroca** [comment]
I've tried the latest version and it's working correctly now
I think this change fixed it: https://github.com/ReactJSResources/react-webpack-babel/commit/851b080c7daf868da77b4e4cb996d57d4f2a0782#diff-e56633f72ecc521128b3db6586074d2c

**Comment by sadnessOjisan** [comment]
me too. 

I use `babel-plugin-module-resolver`  v3.1.1.

```
import {combineReducers} from "redux";

console.log("combineReducers: ", combineReducers)

///

combineReducers: undefined
```
