### ISSUE TITLE
Built files don't work when the project is not served from the server root

### ISSUE THREAD

**Issue by ovidiumght** [ReactJSResources/react-webpack-babel#312]
If I serve the app from http://localhost:9001 (after it was built) it works.
But if I serve it from http://localhost:9001/a/b/index.html, the react app doesn't render. 

All the generated scripts load correctly with a status of 200, but all I see is a blank screen. 

Any idea on how to fix this?

**Comment by alicoding** [comment]
Make sure you change the path in your webpack base config to where the base will be

```
  output: {
    publicPath: '/react/',
    chunkFilename: '[name].bundle.js',
    filename: '[hash:8].bundle.js'
  },
```
if that's done and it doesn't work let me know.

**Comment by ovidiumght** [comment]
The problem is I don't know what the path will be. I need it to work either in http://test.com/a, or http://test.com/b/a, etc. (This is for a WordPress plugin, so I won't host it). 

Isn't there a way to load scripts relative to index.html?

**Comment by ovidiumght** [comment]
Ok, the actual problem was created by the routes. I don't need routes anyway, so with that removed everything is ok.

Thank you, this can be closed.
