### ISSUE TITLE
Need more details about structure setup

### ISSUE THREAD

**Issue by a-barbieri** [ReactJSResources/react-webpack-babel#314]
Hi, I'm new to React. I've been experimenting with your starter kit and it's definitely a great starting point, though I feel you are taking for granted something that I don't know.

One thing I haven't understood is how should I set up the application structure and routing.

I can see that `App` is used inside `index.jsx` whereas `About` and `Sample` are not. That makes me think I should use `App` as a sort of container for the entire application, but then `About` and `Sample` aren't children of `App`.

So I was going to create a `Homepage` component, keep every component separated as I'm used to do on standard MVC applications, but I cannot ditch `App` as it's used inside the hot module replacement and clearly it's a requirement. 

Now I'm stuck. What should I do? How this kit is expecting to be structured? 

Maybe I'm taking this from the wrong perspective. I'm used to work with Rails **static routing system** where there is a correspondence between route and view through the controller. 

Thanks in advance.

**Comment by alicoding** [comment]
Hi,

Great question! In React there are multiple ways you can go about doing what you want.

One way we are doing in on of our production application is following this pattern

```
const Routes = () => (
      <Main>
        <Switch>
          <Route exact path="/" component={HomePage} />
          <Route path="/another-sub-page" component={JustAnotherPage} />
          <Route path="/about-page" component={About} />
        </Switch>
      </Main>
    );
```

Now, `Main` component is basically a wrapper to our application which is just a header and a footer and whatever inside there will be the `children` in this case.

**Comment by a-barbieri** [comment]
Cool!

I've updated the code, but still `App` doesn't contain anything, it's just a place in which I put default styles. Is it right?

```javascript
import Header from "./header";
import Footer from "./footer";

class Main extends Component {
  render() {
    return (
      <div className="Main">
        <Header />
        {this.props.children}
        <Footer />
      </div>
    );
  }
}

class Routes extends Component {
  render() {
    return (
        <Main>
          <Route exact path="/" component={Home} />
          <Route path="/another-sub-page" component={JustAnotherPage} />
          <Route path="/about-page" component={About} />
        </Main>
    );
  }
}

export default Routes;
```

```javascript
import React, { Component } from "react";

import "normalize.css";

import "styles/base/_main.sass"; // Global styles
import "styles/base/_common.sass"; // Global styles
import styles from "./app.sass"; // Css-module styles

class App extends Component {
  render() {
    return (
      <div className="App">
        Nothing in here...
      </div>
    );
  }
}

export default App;
```

**Comment by alicoding** [comment]
Sorry for the delay, but where do you use `App` component right now?

**Comment by a-barbieri** [comment]
I don't... I tried to delete it but it throws a error.

```
[./src/index.jsx] ./src/index.jsx 2.64 kB {0} [built]
[./src/routes.jsx] ./src/routes.jsx 3.86 kB {0} [built]
    + 573 hidden modules

ERROR in ./src/index.jsx
Module not found: Error: Can't resolve './app' in '/Users/ab/Sites/paravicini/src'
 @ ./src/index.jsx 72:2-91:4 73:18-34
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8080 webpack/hot/dev-server core-js/fn/promise core-js/es6/object core-js/es6/array react-hot-loader/patch ./src/index.jsx
Child html-webpack-plugin for "index.html":
     1 asset
```

I think it's due to this lines:

```javascript
// ./index.jsx
// Hot Module Replacement API
if (module.hot) {
  module.hot.accept("./app", () => {
    const NextApp = require("./app").default;
    ReactDOM.render(
      <AppContainer>
        <Provider store={store}>
          <I18nextProvider i18n={i18n}>
            <ConnectedRouter history={history}>
              <NextApp />
            </ConnectedRouter>
          </I18nextProvider>
        </Provider>
      </AppContainer>,
      document.getElementById("app")
    );
  });
}
```

Honestly I haven't investigated much as it's already a pretty stiff learning curve understanding React basic steps. I don't even know if my app is making use of it.

Can I just replace `./app` with another file? Maybe `./home`? Not sure what is its purpose.

**Comment by a-barbieri** [comment]
I've just seen @LeonardoGentile has modified [those lines](https://github.com/ReactJSResources/react-webpack-babel/blob/master/src/index.jsx#L17-L22).

```javascript
// Webpack Hot Module Replacement API
if (module.hot) {
  module.hot.accept('./routes', () => {
    renderApp(require('./routes').default);
  })
}
```

I've updated my code accordingly and now I'm able to ditch `app.jsx`.

**Comment by a-barbieri** [comment]
BTW the `main` class in the solution I posted above leads to the **Block Updating issue**. To solve this read [this guide](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md)
