### ISSUE TITLE
Error in build process: ERROR in multi ./src/index.jsx ./styles/index.scss

### ISSUE THREAD

**Issue by rweller59** [ReactJSResources/react-webpack-babel#315]
I've been having problems with styles when using webpack so I downloaded this project hoping it would lead me in the right direction. Haven't changed any code.
npm start works fine.
npm run build errors with the following:
ERROR in multi ./src/index.jsx ./styles/index.scss
Module not found: Error: Can't resolve './styles/index.scss' in 'C:\Users\Rick\Documents\iotWebDevelopment\react-webpack-babel'
 @ multi ./src/index.jsx ./styles/index.scss

ERROR in ./src/app.jsx
Module not found: Error: Can't resolve 'styles/base/_common.sass' in 'C:\Users\Rick\Documents\iotWebDevelopment\react-webpack-babel\src'
 @ ./src/app.jsx 19:0-35
 @ ./src/routes.jsx
 @ ./src/index.jsx
 @ multi ./src/index.jsx ./styles/index.scss

ERROR in ./src/app.jsx
Module not found: Error: Can't resolve 'styles/base/_main.sass' in 'C:\Users\Rick\Documents\iotWebDevelopment\react-webpack-babel\src'
 @ ./src/app.jsx 17:0-33
 @ ./src/routes.jsx
 @ ./src/index.jsx
 @ multi ./src/index.jsx ./styles/index.scss

**Comment by alicoding** [comment]
I just submitted a PR to fix this issue. Thanks for reporting this.

**Comment by alicoding** [comment]
https://github.com/ReactJSResources/react-webpack-babel/pull/316
