### ISSUE TITLE
Not able to import fontawesome with standard loading configuration

### ISSUE THREAD

**Issue by emhamzahazeen** [ReactJSResources/react-webpack-babel#317]
Installed font awesome:
`yarn add font-awesome@4.7.0 --exact
`
Simple Import in Index.jsx with:
`import 'font-awesome/css/font-awesome.min.css';`

Run npm start

Error:
`ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0
Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css 7:615-666
 @ ./node_modules/font-awesome/css/font-awesome.min.css
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server core-js/fn/promise core-js/es6/object core-js/es6/array ./src/index.jsx

ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0
Module parse failed: Unexpected character ' ' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css 7:526-578
 @ ./node_modules/font-awesome/css/font-awesome.min.css
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server core-js/fn/promise core-js/es6/object core-js/es6/array ./src/index.jsx

ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0
Module parse failed: Unexpected character ' ' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css 7:435-488
 @ ./node_modules/font-awesome/css/font-awesome.min.css
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server core-js/fn/promise core-js/es6/object core-js/es6/array ./src/index.jsx

ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0
Module parse failed: Unexpected character '�' (1:1)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css 7:250-301
 @ ./node_modules/font-awesome/css/font-awesome.min.css
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server core-js/fn/promise core-js/es6/object core-js/es6/array ./src/index.jsx

ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.eot
Module parse failed: Unexpected character '�' (1:1)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css 7:327-370
 @ ./node_modules/font-awesome/css/font-awesome.min.css
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server core-js/fn/promise core-js/es6/object core-js/es6/array ./src/index.jsx

ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <?xml version="1.0" standalone="no"?>
| <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
| <svg>
 @ ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css 7:707-758
 @ ./node_modules/font-awesome/css/font-awesome.min.css
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server core-js/fn/promise core-js/es6/object core-js/es6/array ./src/index.jsx
Child html-webpack-plugin for "index.html":
     2 assets
       4 modules`

**Comment by alicoding** [comment]
The problem here is the config being ignored for `node_modules`

https://github.com/ReactJSResources/react-webpack-babel/blob/58a5fa90d993a84ddce8f9421af64fab878540d4/webpack.loaders.js#L53-L66

**Comment by LeonardoGentile** [comment]
This might have been my fault cause I've recently submitted a PR for this 😆 
I assumed all the fonts to be installed locally

This is a starter and for sure it can't satisfy everybody's needs, it should be modified for each project, but still probably most fonts are installed via npm so should we change this default? @alicoding what do you think?

**Comment by alicoding** [comment]
@Leocardoso94 hehe no worries I guess we could just remove that exclusion or we could just document this somehow?

**Comment by emhamzahazeen** [comment]
Being a starter, it should not 'assume' things in my view.

**Comment by LeonardoGentile** [comment]
@alicoding you just mentioned someone else 😆 
@emhamzahazeen without assumption the starter would not work for the majority of people, it would just not work for anybody IMO.

I've checked and the font loaders were excluding the node_packages even before my PR, but honestly I don't know what's the percentage of people loading font from npm vs locals, so fixing it for some people would break things for others, do you see my point @emhamzahazeen ?

**Comment by alicoding** [comment]
Oopsy! So many people in my list and I just assumed the first one :P

**Comment by emhamzahazeen** [comment]
@LeonardoGentile Maybe have two versions, one commented accordingly with instructions, and current one being the active one?

**Comment by riabhatia24** [comment]
I tried using the [react-audio-player](https://www.npmjs.com/package/react-audio-player) but gave me the similar error for mp3 files.
_Module parse failed: Unexpected token 
You may need an appropriate loader to handle this file type.
| 
| 
|_ 

How can I make the audio
 library work?
