### ISSUE TITLE
Not able to render graph component

### ISSUE THREAD

**Issue by rweller59** [ReactJSResources/react-webpack-babel#318]
Working graphs without webpack (react-timeseries-charts).  Needed to start using webpack so I used this starter project. Graph only partially renders (labeled x-axis only) now.

Simple test using graph sample code and including in navigation page...
```
/const Navigation = () => (
//  <div>
//    <ul>
//      <li><Link to="/">Home</Link></li>
//      <li><Link to="/about">About</Link></li>
//      <li><Link to="/sample">Sample</Link></li>
//    </ul>
//    <ChartTest/>
//  </div>
//);
```

**Comment by alicoding** [comment]
Could you provide more information about what you're trying to do here? Or maybe create a branch of your work and share them.

**Comment by alicoding** [comment]
I'll try to create a branch and see if I can replicate the same issue here.
