### ISSUE TITLE
`yarn run build` on our production cannot find SCSS variables

### ISSUE THREAD

**Issue by a-barbieri** [ReactJSResources/react-webpack-babel#320]
Hi, I'm not able to run `yarn run build` on our production server.
We have several errors now that we've started using `scss` inside each component file.

```
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?sourceMap&localIdentName=[local]___[hash:base64:5]!node_modules/sass-loader/lib/loader.js?outputStyle=expanded!styles/components/_header.scss:
       1 module

    ERROR in ./node_modules/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./node_modules/sass-loader/lib/loader.js?outputStyle=expanded!./styles/components/_header.scss
    Module build failed:
    	background-color: $offwhite-color;
                      ^
          Undefined variable: "$offwhite-color".
          in /home/foo_deploy/app/styles/components/_header.scss (line 10, column 20)
```

I noticed that you have been usign `.sass` files, but I just cannot work with that syntax so I'm now using only `.scss` files.

I don't know if is a bug or some sort of misconfiguration.

Here is the `webpack.production` file. Locally everything works.

**Comment by alicoding** [comment]
I'll take a look and get back to you ASAP.

**Comment by a-barbieri** [comment]
I don't know if I've done something wrong, but just deleting [those lines](https://github.com/ReactJSResources/react-webpack-babel/blob/master/webpack.production.config.js#L8-L12) from `webpack.production.config` everything works fine.


```javascript
loaders.push({
  test: /\.scss$/,
  loader: ExtractTextPlugin.extract({fallback: 'style-loader', use: 'css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!sass-loader?outputStyle=expanded'}),
  exclude: ['node_modules']
});
```

**Comment by LeonardoGentile** [comment]
On a [PR](#311) I've submitted a month or so ago [I've removed](https://github.com/ReactJSResources/react-webpack-babel/pull/311/files#diff-11e9f7f953edc64ba14b0cc350ae7b9dL12) any extra loaders pushed from within the webpack.config.js file so that now all loaders are defined in the separate file webpack.loaders.js.

I've done this in the dev version only of weback conf (webpack.loaders.js) and I forgot to do the 
 same for the webpack.production.config.

So I guess removing those lines should be correct, although I don't have much experience with ExtractTextPlugin so I a second opinion on this would be appreciated from someone with more experience.

**Comment by a-barbieri** [comment]
@LeonardoGentile, then both `development` and `production` loaders configuration were the same before you remove all loaders?

**Comment by LeonardoGentile** [comment]
Not exactly.
What I've removed form `webpack.config.js`:

```
loaders.push({  
  test: /\.scss$/, 
  loaders: ['style-loader', 'css-loader?importLoaders=1', 'sass-loader'],  
  exclude: ['node_modules']  
});
```
I'm not sure why this single loaders was pushed from from within webpack config and was not inside the webpack.loaders as all the others, so I moved it there as long as many other changes.

What you've removed from `webpack.production.config`

```
loaders.push({
  test: /\.scss$/,
  loader: ExtractTextPlugin.extract({fallback: 'style-loader', use: 'css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!sass-loader?outputStyle=expanded'}),
  exclude: ['node_modules']
});
```

Given I haven't played much with ExtractTextPlugin So I'm not 100% sure of the implications of removing this last block from `webpack.production.config`.

**Comment by pgerochi** [comment]
This is fixed in the new updated master branch.
