### ISSUE TITLE
Absolute system paths in js from output bundle

### ISSUE THREAD

**Issue by Suvitruf** [ReactJSResources/react-webpack-babel#321]
After building production package with `npm run build`, I opened produced js file and found absolute system paths like this:

`t.register(a,"default","D:/texts/Sources/react-webpack-babel/src/components/Sample.jsx")`

Why are there absolute paths? How can I remove/fix them?

**Comment by alicoding** [comment]
Could you share your snippet of code or an error you're getting as well?

**Comment by Suvitruf** [comment]
Looks like it's 'cause of react-hot-loader.

**Comment by LeonardoGentile** [comment]
I see, Have you tried removing react-hot-loader and see if it fixes the problem? In that case we'll know where to look

**Comment by LeonardoGentile** [comment]
@Suvitruf can you share your SO question.
Did you find any explanation why this is happening?

**Comment by Suvitruf** [comment]
@LeonardoGentile https://stackoverflow.com/q/52040299/1991579
No =/

**Comment by pgerochi** [comment]
This has been fixed in the new release
