### ISSUE TITLE
SCSS files/syntax not working

### ISSUE THREAD

**Issue by eoy4** [ReactJSResources/react-webpack-babel#323]
Just cloned and started using the project.  I created a `.scss` test file containing this
```scss
.blueButton {
    background: blue;
}
```
 and imported it in `app.jsx` like this
```jsx
import "styles/base/style.scss"  // SCSS test
```
I'm getting these errors with webpack build:
```
ERROR in ./node_modules/css-loader??ref--9-1!./node_modules/postcss-loader/lib??ref--9-2!./node_modules/sass-loader/lib/loader.js??ref--9-3!./node_modules/sass-resources-loader/lib/loader.js??ref--9-4!./styles/base/style.scss
Module build failed: 
undefined
            ^
      Invalid CSS after ".blueButton {": expected "}", was "{"
      in /Users/{...}/styles/base/style.scss (line 17, column 14)
 @ ./styles/base/style.scss 4:14-265 18:2-22:4 19:20-271
 @ ./src/app.jsx
 @ ./src/routes.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server core-js/fn/promise core-js/es6/object core-js/es6/array ./src/index.jsx
```

I'm thinking `sass-loader` is interpreting it as SASS indented syntax.  I want to use SCSS syntax in my project, but don't know where to look to start fixing this problem. Is this a bug, or am I missing something?

**Comment by LeonardoGentile** [comment]
I would probably start looking the loader [config](https://github.com/ReactJSResources/react-webpack-babel/blob/master/webpack.loaders.js#L166) and the [sass-loader doc](https://github.com/webpack-contrib/sass-loader)

**Comment by LeonardoGentile** [comment]
relevant: https://github.com/webpack-contrib/sass-loader/issues/187

**Comment by eoy4** [comment]
@LeonardoGentile thanks for your pointers!

I tried removing this option from the loader
```js
indentedSyntax: "sass"
```
and I imported the loader like this
```js
loader: "sass-loader"?indentedSyntax=false
```
and always got the same errors.

I removed all `.sass` files and only created and imported `.scss` files and now I'm getting these errors

```
ERROR in ./node_modules/css-loader??ref--9-1!./node_modules/postcss-loader/lib??ref--9-2!./node_modules/sass-loader/lib/loader.js??ref--9-3!./node_modules/sass-resources-loader/lib/loader.js??ref--9-4!./styles/base/style.scss
Module build failed: Error: 
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.
    
    at Object.module.exports (/Users/{...}/node_modules/sass-resources-loader/lib/loader.js:73:18)
 @ ./styles/base/style.scss 4:14-265 18:2-22:4 19:20-271
 @ ./src/app.jsx
 @ ./src/routes.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server core-js/fn/promise core-js/es6/object core-js/es6/array ./src/index.jsx
```

Call me crazy, but shouldn't SCSS files just work out of the box with the provided configs?

**Comment by eoy4** [comment]
@alicoding Thanks!! this config works for me.

Still, I think this is an issue since the project claims to support sass and scss files. I'm not closing the issue right now for this reason.

**Comment by alicoding** [comment]
@eoy4 do you mind update the config and make a pull request for that :)

**Comment by eoy4** [comment]
@alicoding I removed some things from my config, like css modules. I'll try to identify the change that fixes the SCSS issue and do a PR with it

**Comment by alicoding** [comment]
👍

**Comment by pgerochi** [comment]
This is fixed in the new version.
