### ISSUE TITLE
This boilerplate is actually well over 200MB

### ISSUE THREAD

**Issue by bever1337** [ReactJSResources/react-webpack-babel#337]
Super excited by this project, I love the idea of simplifying React projects. I was drawn in by the Readme suggesting 200MB was a huge size for a project's dependencies; but unfortunately the size of this project is well over 200MB.

Expected Result: An application at least under 200MB and without a bunch of dependencies
Result: Dependencies take up 1.75x more disk space than advertised

![image](https://user-images.githubusercontent.com/28774413/75398537-f4fa4500-58c7-11ea-8858-635b5d9fcbb6.png)

**Comment by pgerochi** [comment]
Hey @bever1337 - First of all, thank you for holding us accountable. Secondly, I tried to lower this as much as I can, 219.3MB to be exact. I've deleted unused dependencies and only prioritized what is needed but unfortunately that's the lowest it can go so I've changed the readme to reflect that it is lower than 250mb. Again thanks for the feedback.
